### ISSUE TITLE
Fails on Windows 10

### ISSUE THREAD

**Issue by davidmurdoch** [heroku/heroku-certs#14]
`npm install heroku-certs` fails with 

npm ERR! tar.unpack untar error C:\Users\***\AppData\Local\heroku\npm\heroku-certs\1.1.12\package.tgz
npm WARN plugins No description
npm WARN plugins No repository field.
npm WARN plugins No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\***\\AppData\\Local\\heroku\\cli\\lib\\node.exe" "C:\\Users\\***\\AppData\\Local\\heroku\\cli\\lib\\npm\\cli.js" "install" "heroku-certs" "--loglevel=info"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! path C:\Users\***\AppData\Local\heroku\plugins\node_modules\.staging\heroku-certs-e1807e29\*.thawing-temple-8799.com.key
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\***\AppData\Local\heroku\plugins\node_modules\.staging\heroku-certs-e1807e29\*.thawing-temple-8799.com.key'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\***\AppData\Local\heroku\plugins\node_modules\.staging\heroku-certs-e1807e29\*.thawing-temple-8799.com.key'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by ransombriggs** [comment]
@davidmurdoch I released a new version, could you please try `heroku plugins:install heroku-certs` again?

**Comment by davidmurdoch** [comment]
Installed! Thanks!
