### ISSUE TITLE
Type for Private Spaces app

### ISSUE THREAD

**Issue by zunda** [heroku/heroku-certs#29]
It is sometimes confusing that Type for an endpoint on a Private Spaces app is shown as `Endpoint` while SSL Endpoint add-on is not required on the app and SNI extension is required on client. Might it be possible to show Type as, say, `Private Spaces` for such an app to avoid confusion.

**Comment by ransombriggs** [comment]
@brettgoulder what do you think of this, I would be fine displaying something different for private space managed certificates, just want your sign off first and name suggestions before I change anything.

**Comment by brettgoulder** [comment]
@ransombriggs Makes sense, we can differentiate it like that 👍

**Comment by zunda** [comment]
As a replacement for `SNI` (Free SSL) and `Endpoint` (SSL:Endpoint), `Private Space app` seems legit, as the load balancer is per app.
