### ISSUE TITLE
should be written with standard

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/heroku-certs#5]
since this will be a core plugin, it should be in standard.js like the others. This doesn't have to happen before GA, but should at some point.

**Comment by ransombriggs** [comment]
@dickeyxxx this has been fixed in https://github.com/heroku/heroku-certs/commit/85b68c438844164259dd7dbcdeb4a2d495cea502

**Comment by dickeyxxx** [comment]
wow great! hopefully that wasn't too much of a hassle
