### ISSUE TITLE
help descriptions are too long

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/heroku-certs#6]
ideally these should fit in 80 characters:

![screen shot 2016-05-10 at 3 30 09 pm](https://cloud.githubusercontent.com/assets/216188/15164513/1c7c4500-16c4-11e6-9038-c8faf056fb70.png)

also, they should not begin with uppercase characters or end in periods (as described in the style guide)

**Comment by ransombriggs** [comment]
Proposed fix is in https://github.com/heroku/heroku-certs/pull/9
