### ISSUE TITLE
Add help for commands

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/heroku-certs#7]
I think most of these would benefit from adding help with examples since they're not obvious how to use. Especially for `certs:add`, `certs:generate`, `certs:key`, and `certs:update`

**Comment by dickeyxxx** [comment]
Some consistency around capitalization would be good with `SSL` and maybe other acronyms

**Comment by dickeyxxx** [comment]
Maybe this is my fault, but it isn't clear what `--name` is for with `certs:info`. Is it the CNAME?

**Comment by ransombriggs** [comment]
@dickeyxxx name is the first column in the `_certs` command table, I had to add it to uniquely identify the SNI endpoint since they have plans to allow multiples in the future

**Comment by dickeyxxx** [comment]
do you have an app I can test on?

**Comment by ransombriggs** [comment]
@dickeyxxx thawing-temple-8799 - I just added you as a collaborator

**Comment by ransombriggs** [comment]
@dickeyxxx Take a look at this issue https://github.com/heroku/heroku-certs/issues/4, we had talked about making the info / remove / update take a arg instead of a name flag.  Would that make things more consistent ?

**Comment by ransombriggs** [comment]
I had left that issue unimplemented because there were changes being made around endpoint that I was waiting to clear up before I could implement things properly.

**Comment by ransombriggs** [comment]
@dickeyxxx I search the help for instances where SSL was not all caps and could not find any.  Where did you see the inconsistencies?

**Comment by ransombriggs** [comment]
@dickeyxxx does the name flag make more sense now?  The name column was added in this plugin to the listing of certificates, here is the example for my app.
```
-> % heroku _certs --app thawing-temple-8799
Name                 Common Name(s)  Expires               Trusted  Type
───────────────────  ──────────────  ────────────────────  ───────  ────
dilophosaurus-82906  example.com     2016-06-12 14:57 UTC  False    SNI
```
Do you think I should explicitly point them at the `_certs` command in the `--name` description to help eliminate confusion?

**Comment by dickeyxxx** [comment]
yeah I think it makes sense now

**Comment by dickeyxxx** [comment]
@ransombriggs actually the inconsistencies might be with `certs` not `_certs`

**Comment by ransombriggs** [comment]
Not a problem, closing.
